blank_issues_enabled: false
contact_links:
  - name: Discuss a deprecation
    url: https://github.com/azure-deprecation/dashboard/discussions/new
    about: Discuss an Azure deprecation notice with others